# Generated by Django 3.2 on 2021-05-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
