# Generated by Django 3.2 on 2021-05-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_messages_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
