# Generated by Django 3.2 on 2021-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0003_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=50)),
                ('isGroup', models.BooleanField(default=False)),
                ('groupId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('reader', models.CharField(max_length=50)),
                ('onGroup', models.BooleanField(default=False)),
                ('groupId', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
