# Generated by Django 3.2 on 2021-05-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_messages_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='onGroup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='reader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
