# Generated by Django 3.2 on 2021-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20210513_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='owner',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
