# Generated by Django 3.2 on 2021-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_userstatus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='typing_status',
            field=models.BooleanField(default=False),
        ),
    ]
