# Generated by Django 3.2 on 2021-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_alter_userstatus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
