# Generated by Django 3.2 on 2021-05-31 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='groupId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
