# Generated by Django 3.2 on 2021-05-31 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20210531_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groupName', models.TextField(unique=True)),
                ('owner', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('protectedStatus', models.BooleanField(default=False)),
                ('members', models.TextField(blank=True)),
                ('totalMembers', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
