# Generated by Django 3.2 on 2021-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='groupStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='groupId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
