# Generated by Django 3.2 on 2021-06-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_auto_20210603_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='groupId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
